/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  gcc_test                               */
/*      FILE         :  gcc_test.cpp                           */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include <iodefine.h>
#include <vector>
#include <array>
#include <TUT_BasicSource/header/setup.h>
#include <Led/Led.h>
#include <UART/UART0.h>
#include <functional>
#include <interrupt_handlers.h>

extern std::function< void() > int_excep_sci0_rxi0;

#ifdef CPPAPP
//Initialize global constructors
extern void __main()
{
  static int initialized;
  if (! initialized)
    {
      typedef void (*pfunc) ();
      extern pfunc __ctors[];
      extern pfunc __ctors_end[];
      pfunc *p;

      initialized = 1;
      for (p = __ctors_end; p > __ctors; )
    (*--p) ();

    }
}
#endif 

#define NUM 10

UART *uart_print;

void attach(std::function< void() > *function, void (*function_ptr)())
{
	*function = function_ptr;
}

void interrupt_function(){
	unsigned char data;
	data = SCI0.RDR;
	uart_print->Printf("again, world\n");
}

int main(void) {
	setup();
	std::vector<int> a;
	int b[NUM];
	std::array<int, NUM> c;
	Led *led = new Led1();
	uart_print = new UART0(UART::B115200, UART::SCI_BUFFERSIZE);
	attach(&int_excep_sci0_rxi0, interrupt_function);

	for(auto i = 0; i < NUM; i++){
		a.push_back(i);
		b[i] = a[i];
		c[i] = a[i];
	}

	led->output(true);
	uart_print->Printf("hello, world!\n");
	uart_print->Printf("thank you, world!\n");

	for(auto i = 0; i < 0; i++);

	while(1) {

	// TODO: add application code here
    }
return 0;
}
